modLoader = "javafml"
loaderVersion = "[43,)"
license = "LGPL-3.0"
issueTrackerURL = "https://github.com/SamsTheNerd/inline/issues"
showAsResourcePack = false

[[mods]]
modId = "inline"
version = "${mod_version}"
displayName = "Inline"
displayURL = "https://github.com/SamsTheNerd/inline"
logoFile = "icon.png"
authors = "samsthenerd"
description = "A library for rendering in line with text"

[[dependencies.inline]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

  [[dependencies.inline]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

  [[dependencies.inline]]
    modId="cloth_config"
    mandatory=true
    versionRange="[11.0.0,)"
    ordering="NONE"
    side="CLIENT"