modLoader = "javafml"
loaderVersion = "${loader_version}"
license = "LGPL-3.0"
issueTrackerURL = "https://github.com/SamsTheNerd/inline/issues"
showAsResourcePack = false

[[mods]]
modId = "inline"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/SamsTheNerd/inline"
logoFile = "assets/inline/icon.png"
authors = "samsthenerd"
description = '''
${description}
'''

[[mixins]]
config = "inline.mixins.json"

[[dependencies.inline]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_dependency}"
ordering = "NONE"
side = "BOTH"

[[dependencies.inline]]
modId = "fabric_api"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.inline]]
modId = "configurable"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.inline]]
modId = "emojiful"
type = "incompatible"
versionRange = "*"
ordering = "NONE"
side = "BOTH"