modLoader = "javafml"
loaderVersion = "[4,)"
license = "LGPL-3.0"
issueTrackerURL = "https://github.com/SamsTheNerd/inline/issues"
showAsResourcePack = false

[[mods]]
modId = "inline"
version = "${mod_version}"
displayName = "Inline"
displayURL = "https://github.com/SamsTheNerd/inline"
logoFile = "assets/inline/icon.png"
authors = "samsthenerd"
description = "A library for rendering in line with text"

[[mixins]]
config = "inline-forge.mixins.json"
[[mixins]]
config = "inline-common.mixins.json"

[[dependencies.inline]]
    modId="neoforge"
    mandatory=true
    versionRange="[21,)"
    ordering="NONE"
    side="BOTH"

  [[dependencies.inline]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"

  [[dependencies.inline]]
    modId="cloth_config"
    mandatory=true
    versionRange="[15.0.0,)"
    ordering="NONE"
    side="CLIENT"

  [[dependencies.inline]]
    modId = "emojiful"
    type = "incompatible"
    versionRange = "*"
    ordering = "NONE"
    side = "BOTH"
